var product = [{
    "id": 0,
    "title": "",
    "price": "",
    "oncampusliving": "",
    "acceptancerate": "",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png",
    "earlyaction": "",
    "earlydecision": "",
    "is": "",
    "gpa": "",
    "satmath": "",
    "sate": "",
    "rad": "",
    "act": "",
    "qs": "",
    "is": "",
    "p": "",
}, {
    "id": 1,
    "title": "Massachusetts Institute of Technology (MIT)",
    "price": 60156,
    "totalprice": 82730,
    "oncampusliving": "Yes",
    "acceptancerate": "4% of 33,767 applicants were admitted",
    "image": "mit.png",
    "earlyaction": "Yes",
    "earlydecision": "No",
    "gpa": "-",
    "satmath": "790-800 range of middle 50%",
    "sate": "730-780 range of middle 50%",
    "rad": "January 1",
    "act": "35-36 range of middle 50%",
    "qs": "1",
    "is": "11.0% from 107 countries",
    "location": "Cambridge, Massachusetts",
    "p": "Private",
},
{
    "id": 2,
    "title": "Harvard University",
    "price": 59076,
    "totalprice": 82950,
    "oncampusliving": "Yes",
    "acceptancerate": "3% of 61,221 applicants were admitted",
    "image": "harvard.png",
    "earlyaction": "Yes",
    "earlydecision": "No",
    "gpa": "4",
    "satmath": "760-800 range of middle 50%",
    "sate": "730-780 range of middle 50%",
    "rad": "January 1",
    "act": "34-36 range of middle 50%",
    "qs": "4",
    "is": "13.1% from 114 countries",
    "location": "Cambridge, Massachusetts",
    "p": "Private",
},
{
    "id": 3,
    "title": "Stanford University",
    "price": 62454,
    "totalprice": 86831,
    "oncampusliving": "Yes",
    "acceptancerate": "4% of 56,378 applicants were admitted",
    "image": "stanford.png",
    "earlyaction": "Yes",
    "earlydecision": "No",
    "gpa": "3.95",
    "satmath": "770-800 range of middle 50%",
    "sate": "730-780 range of middle 50%",
    "rad": "January 5",
    "act": "33-35 range of middle 50%",
    "qs": "5",
    "is": "5.6%",
    "location": "Stanford, California",
    "p": "Private",
},
{
    "id": 4,
    "title": "University of California, Berkeley (UCB)",
    "price": 48127,
    "totalprice": 78457,
    "oncampusliving": "Yes",
    "acceptancerate": "11% of 125,130 applicants were admitted",
    "image": "berkely.png",
    "earlyaction": "No",
    "earlydecision": "No",
    "gpa": "3.9",
    "satmath": "Test Free",
    "sate": "Test Free",
    "rad": "November 30",
    "act": "Test Free",
    "qs": "10",
    "is": "12.7%",
    "location": "Berkeley, California",
    "p": "Public",
},
{
    "id": 5,
    "title": "University of Chicago",
    "price": 65619,
    "totalprice": 89490,
    "oncampusliving": "Yes",
    "acceptancerate": "5% of 37,522 applicants were admitted",
    "image": "uchicago.png",
    "earlyaction": "No",
    "earlydecision": "Yes",
    "gpa": "4",
    "satmath": "760-800 range of middle 50%",
    "sate": "740-780 range of middle 50%",
    "rad": "January 2",
    "act": "34-35 range of middle 50%",
    "qs": "11",
    "is": "15.9% from 125 countries",
    "location": " Chicago, Illinois",
    "p": "Private",
},
{
    "id": 6,
    "title": "University of Pennsylvania",
    "price": 66104,
    "totalprice": 89028,
    "oncampusliving": "Yes",
    "acceptancerate": "7% of 54,588 applicants were admitted",
    "image": "upenn.png",
    "earlyaction": "No",
    "earlydecision": "Yes",
    "gpa": "3.9 (based on weighted GPAs)",
    "satmath": "770-800 range of middle 50%",
    "sate": "730-770 range of middle 50%",
    "rad": "January 5",
    "act": "34-35 range of middle 50%",
    "qs": "12",
    "is": "13.4% from 109 countries",
    "location": "Philadelphia, Pennsylvania",
    "p": "Private",
}, 
{
    "id": 7,
    "title": "Cornell University",
    "price": 66014,
    "totalprice": 87786,
    "oncampusliving": "Yes",
    "acceptancerate": "7% of 71,164 applicants were admitted",
    "image": "cornell.png",
    "earlyaction": "No",
    "earlydecision": "Yes",
    "gpa": "-",
    "satmath": "750-800 range of middle 50%",
    "sate": "710-770 range of middle 50%",
    "rad": "January 2",
    "act": "33-35 range of middle 50%",
    "qs": "13",
    "is": "7.3%",
    "location": "Ithaca, New York",
    "p": "Private",
},
{
    "id": 8,
    "title": "California Institute of Technology",
    "price": 63255,
    "totalprice": 87386,
    "oncampusliving": "Yes",
    "acceptancerate": "3% of 16,626 applicants were admitted",
    "image": "caltech.png",
    "earlyaction": "Yes",
    "earlydecision": "No",
    "gpa": "-",
    "satmath": "-",
    "sate": "-",
    "rad": "January 3",
    "act": "-",
    "qs": "15",
    "is": "9.4% from 36 countries",
    "location": "Pasadena, California",
    "p": "Private",
},
{
    "id": 9,
    "title": "Yale University",
    "price": 64700,
    "totalprice": 88300,
    "oncampusliving": "Yes",
    "acceptancerate": "5% of 50,060 applicants were admitted",
    "image": "yale.png",
    "earlyaction": "Yes",
    "earlydecision": "No",
    "gpa": "-",
    "satmath": "760-800 range of middle 50%",
    "sate": "740-780 range of middle 50%",
    "rad": "January 2",
    "act": "33-35 range of middle 50%",
    "qs": "16",
    "is": "10.4% from 119 countries",
    "location": "New Haven, Connecticut",
    "p": "Private",
},
{
    "id": 10,
    "title": "Princeton University",
    "price": 59710,
    "totalprice": 84540,
    "oncampusliving": "Yes",
    "acceptancerate": "6% of 38,019 applicants were admitted",
    "image": "princeton.png",
    "earlyaction": "Yes",
    "earlydecision": "No",
    "gpa": "3.95",
    "satmath": "760-800 range of middle 50%",
    "sate": "740-780 range of middle 50%",
    "rad": "January 1",
    "act": "34-35 range of middle 50%",
    "qs": "17",
    "is": "12.2% from 100 countries",
    "location": "Princeton, New Jersey",
    "p": "Private",
},
{
    "id": 11,
    "title": "Columbia University",
    "price": 68400,
    "totalprice": 89845,
    "oncampusliving": "Yes",
    "acceptancerate": "4% of 60,374 applicants were admitted",
    "image": "columbia.png",
    "earlyaction": "No",
    "earlydecision": "Yes",
    "gpa": "-",
    "satmath": "770-800 range of middle 50%",
    "sate": "730-780 range of middle 50%",
    "rad": "January 1",
    "act": "34-35 range of middle 50%",
    "qs": "23",
    "is": "16.0% from 118 countries",
    "location": "New York City, New York",
    "p": "Private",
},
{
    "id": 12,
    "title": "Johns Hopkins University",
    "price": 63340,
    "totalprice": 86610,
    "oncampusliving": "Yes",
    "acceptancerate": "7% of 37,826 applicants were admitted",
    "image": "hopkins.png",
    "earlyaction": "No",
    "earlydecision": "Yes",
    "gpa": "3.93",
    "satmath": "780-800 range of middle 50%",
    "sate": "740-770 range of middle 50%",
    "rad": "January 2",
    "act": "34-35 range of middle 50%",
    "qs": "28",
    "is": "13.8% from 97 countries",
    "location": "Baltimore, Maryland",
    "is": "Private",
},
{
    "id": 13,
    "title": "University of California, Los Angeles (UCLA)",
    "price": 47428,
    "totalprice": 68797,
    "oncampusliving": "Yes",
    "acceptancerate": "9% of 149,815 applicants were admitted",
    "image": "ucla.png",
    "earlyaction": "No",
    "earlydecision": "No",
    "gpa": "3.93",
    "satmath": "Test Free",
    "sate": "Test Free",
    "rad": "November 30",
    "act": "Test Free",
    "qs": "29",
    "is": "9.1%",
    "location": "Los Angeles, California",
    "p": "Public",
},
{
    "id": 14,
    "title": "University of Michigan-Ann Arbor",
    "price": 55654,
    "totalprice": 74163,
    "oncampusliving": "Yes",
    "acceptancerate": "18% of 84,289 applicants were admitted",
    "image": "umich.png",
    "earlyaction": "No",
    "earlydecision": "No",
    "gpa": "3.9",
    "satmath": "680-780 range of middle 50%",
    "sate": "670-750 range of middle 50%",
    "rad": "February 1",
    "act": "31-34 range of middle 50%",
    "qs": "33",
    "is": "8.3% from 87 countries",
    "location": "Ann Arbor, Michigan",
    "p": "Public",
},
{
    "id": 15,
    "title": "New York University (NYU)",
    "price": 63222,
    "totalprice": 89176,
    "oncampusliving": "Yes",
    "acceptancerate": "12% of 100,662 applicants were admitted",
    "image": "nyu.png",
    "earlyaction": "No",
    "earlydecision": "Yes",
    "gpa": "3.8",
    "satmath": "750-780 range of middle 50%",
    "sate": "720-770 range of middle 50%",
    "rad": "January 5",
    "act": "33-35 range of middle 50%",
    "qs": "38",
    "is": "20.0% from 130 countries",
    "location": "New York City, New York",
    "p": "Public",
},
{
    "id": 16,
    "title": "Northwestern University",
    "price": 65997,
    "totalprice": 91236,
    "oncampusliving": "Yes",
    "acceptancerate": "7% of 51,261 applicants were admitted",
    "image": "northwestern.png",
    "earlyaction": "No",
    "earlydecision": "Yes",
    "gpa": "3.8",
    "satmath": "760-800 range of middle 50%",
    "sate": "730-770 range of middle 50%",
    "rad": "January 3",
    "act": "33-35 range of middle 50%",
    "qs": "38",
    "is": "10.5% from 105 countries",
    "location": "Evanston, Illinois",
    "p": "Private",
},
{
    "id": 17,
    "title": "Carnegie Mellon University",
    "price": 63274,
    "totalprice": 83392,
    "oncampusliving": "Yes",
    "acceptancerate": "11% of 34,261 applicants were admitted",
    "image": "cmu.png",
    "earlyaction": "No",
    "earlydecision": "Yes",
    "gpa": "3.9",
    "satmath": "770-800 range of middle 50%",
    "sate": "720-770 range of middle 50%",
    "rad": "January 3",
    "act": "34-35 range of middle 50%",
    "qs": "52",
    "is": "23.9% from 78 countries",
    "location": "Pittsburgh, Pennsylvania",
    "p": "Private",
},
{
    "id": 18,
    "title": "Duke University",
    "price": 65805,
    "totalprice": 87387,
    "oncampusliving": "Yes",
    "acceptancerate": "6% of 50,016 applicants were admitted",
    "image": "duke.png",
    "earlyaction": "No",
    "earlydecision": "Yes",
    "gpa": "-",
    "satmath": "760-800 range of middle 50%",
    "sate": "730-770 range of middle 50%",
    "rad": "January 2",
    "act": "34-35 range of middle 50%",
    "qs": "57",
    "is": "9.9%",
    "location": "Durham, North Carolina",
    "p": "Private",
},
{
    "id": 19,
    "title": "University of Texas at Austin",
    "price": 41070,
    "totalprice": 59618,
    "oncampusliving": "Yes",
    "acceptancerate": "31% of 59,767 applicants were admitted",
    "image": "uta.png",
    "earlyaction": "No",
    "earlydecision": "No",
    "gpa": "-",
    "satmath": "-",
    "sate": "-",
    "rad": "December 1",
    "act": "-",
    "qs": "58",
    "is": "4.4% from 121 countries",
    "location": "Austin, Texas",
    "p": "Public",
},
{
    "id": 20,
    "title": "University of California, San Diego (UCSD)",
    "price": 50886,
    "totalprice": 71562,
    "oncampusliving": "Yes",
    "acceptancerate": "24% of 131,254 applicants were admitted",
    "image": "ucsd.png",
    "earlyaction": "No",
    "earlydecision": "No",
    "gpa": "-",
    "satmath": "Test Free",
    "sate": "Test Free",
    "rad": "November 30",
    "act": "Test Free",
    "qs": "62",
    "is": "14.0% from 121 countries",
    "location": "San Diego, California",
    "p": "Public",
},
{
    "id": 21,
    "title": "University of Washington",
    "price": 40836,
    "totalprice": 61058,
    "oncampusliving": "Yes",
    "acceptancerate": "48% of 52,488 applicants were admitted",
    "image": "uwash.png",
    "earlyaction": "No",
    "earlydecision": "No",
    "gpa": "3.83",
    "satmath": "660-780 range of middle 50%",
    "sate": "640-740 range of middle 50%",
    "rad": "November 15",
    "act": "29-34 range of middle 50%",
    "qs": "63",
    "is": "11.7% from 79 countries",
    "location": "Seattle, Washington",
    "p": "Public",
},
{
    "id": 22,
    "title": "University of Illinois at Urbana-Champaign",
    "price": 33692,
    "totalprice": 51664,
    "oncampusliving": "Yes",
    "acceptancerate": "45% of 63,257 applicants were admitted",
    "image": "uiuc.png",
    "earlyaction": "No",
    "earlydecision": "No",
    "gpa": "-",
    "satmath": "680-790 range of middle 50%",
    "sate": "660-740 range of middle 50%",
    "rad": "January 5",
    "act": "29-34 range of middle 50%",
    "qs": "64",
    "is": "13.5% from 88 countries",
    "location": "Champaign, Illinois",
    "p": "Public",
},
{
    "id": 23,
    "title": "Brown University",
    "price": 68230,
    "totalprice": 88948,
    "oncampusliving": "Yes",
    "acceptancerate": "5% of 50,649 applicants were admitted",
    "image": "brown.png",
    "earlyaction": "No",
    "earlydecision": "Yes",
    "gpa": "-",
    "satmath": "760-800 range of middle 50%",
    "sate": "730-780 range of middle 50%",
    "rad": "January 3",
    "act": "34-36 range of middle 50%",
    "qs": "73",
    "is": "10.9% from 103 countries",
    "location": "Providence, Rhode Island",
    "p": "Private",
},
{
    "id": 24,
    "title": "Pennsylvania State University",
    "price": 27612,
    "totalprice": 40596,
    "oncampusliving": "Yes",
    "acceptancerate": "55% of 85,478 applicants were admitted",
    "image": "pennstate.png",
    "earlyaction": "Yes",
    "earlydecision": "No",
    "gpa": "-",
    "satmath": "610-710 range of middle 50%",
    "sate": "600-680 range of middle 50%",
    "rad": "November 30",
    "act": "26-31 range of middle 50%",
    "qs": "83",
    "is": "-",
    "location": "University Park, Pennsylvania",
    "p": "Private",
},
{
    "id": 25,
    "title": "Boston University",
    "price": 62360,
    "totalprice": 82760,
    "oncampusliving": "Yes",
    "acceptancerate": "14% of 80,796 applicants were admitted",
    "image": "boston.png",
    "earlyaction": "No",
    "earlydecision": "Yes",
    "gpa": "3.88",
    "satmath": "690-770 range of middle 50%",
    "sate": "660-730 range of middle 50%",
    "rad": "January 4",
    "act": "31-34 range of middle 50%",
    "qs": "93",
    "is": "21.6% from 119 countries",
    "location": "Boston, Massachussets",
    "p": "Private",
},
{
    "id": 26,
    "title": "Georgia Insitute of Technology",
    "price": 32876,
    "totalprice": 52180,
    "oncampusliving": "Yes",
    "acceptancerate": "17% of 50,610 applicants were admitted",
    "image": "georgia.png",
    "earlyaction": "Yes",
    "earlydecision": "No",
    "gpa": "-",
    "satmath": "700-790 range of middle 50%",
    "sate": "670-760 range of middle 50%",
    "rad": "January 4",
    "act": "31-35 range of middle 50%",
    "qs": "97",
    "is": "9.6% from 117 countries",
    "location": "Atlanta, Georgia",
    "p": "Public",
},
{
    "id": 27,
    "title": "Purdue University",
    "price": 23062,
    "totalprice": 41864,
    "oncampusliving": "Yes",
    "acceptancerate": "53% of 68,309 applicants were admitted",
    "image": "purdue.png",
    "earlyaction": "Yes",
    "earlydecision": "No",
    "gpa": "3.74",
    "satmath": "600-760 range of middle 50%",
    "sate": "600-710 range of middle 50%",
    "rad": "January 15",
    "act": "27-34 range of middle 50%",
    "qs": "99",
    "is": "11.2% from 113 countries",
    "location": "West Lafayette, Indiana",
    "p": "Public",
},

]